---

- name: Install xrdp
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - xrdp 
    ansible_connection: ssh
    ansible_host: "{{ prop_ipaddress }}"
  become: true

