---

- name: "Playbook: Build Template"
  hosts: "{{ args_host }}"
  gather_facts: false

  vars_files:
    - /etc/ansible/inventory/vars.yml

  roles:
    - name: alex.preinstall.knownhost
      vars:
        args_ipaddress: "{{ prop_proxmox_host }}"
    - name: alex.proxmox.status
      vars:
        args_vmid: "{{ prop_proxmox_vmid }}"
    - name: alex.proxmox.startvm
      when: '"RUNNING" not in vmstatusresult.stdout'
    - name: alex.preinstall.waitstarted
    - name: alex.preinstall.knownhost
      vars:
        args_ipaddress: "{{ prop_ipaddress }}"
    - name: alex.linuxdesk.installxrdp
    - name: alex.linuxdesk.installremmina
    - name: alex.linuxdesk.installedge
    - name: alex.linuxdesk.installterminal
    - name: alex.linuxdesk.installfilemanager
    - name: alex.linuxdesk.installtexteditor
